version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/backend/financier"
    schedule:
      interval: "weekly"
    reviewers:
      - Welpeth
    assignees:
      - Welpeth
      
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    reviewers:
      - Welpeth
    assignees:
      - Welpeth
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - Welpeth
    assignees:
      - Welpeth
